package pe.edu.upc.entities;
// Generated Jul 1, 2017 12:33:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Actividades generated by hbm2java
 */
public class Actividades  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set proveedoreses = new HashSet(0);

    public Actividades() {
    }

	
    public Actividades(String nombre) {
        this.nombre = nombre;
    }
    public Actividades(String nombre, Set proveedoreses) {
       this.nombre = nombre;
       this.proveedoreses = proveedoreses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProveedoreses() {
        return this.proveedoreses;
    }
    
    public void setProveedoreses(Set proveedoreses) {
        this.proveedoreses = proveedoreses;
    }




}


