package pe.edu.upc.entities;
// Generated 01-jul-2017 17:48:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set servicioses = new HashSet(0);

    public Categorias() {
    }

	
    public Categorias(String nombre) {
        this.nombre = nombre;
    }
    public Categorias(String nombre, String descripcion, Set servicioses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.servicioses = servicioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getServicioses() {
        return this.servicioses;
    }
    
    public void setServicioses(Set servicioses) {
        this.servicioses = servicioses;
    }




}


