package pe.edu.upc.entities;
// Generated 01-jul-2017 17:48:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set provinciases = new HashSet(0);
     private Set servicioses = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(String nombre) {
        this.nombre = nombre;
    }
    public Departamentos(String nombre, Set provinciases, Set servicioses) {
       this.nombre = nombre;
       this.provinciases = provinciases;
       this.servicioses = servicioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProvinciases() {
        return this.provinciases;
    }
    
    public void setProvinciases(Set provinciases) {
        this.provinciases = provinciases;
    }
    public Set getServicioses() {
        return this.servicioses;
    }
    
    public void setServicioses(Set servicioses) {
        this.servicioses = servicioses;
    }




}


