package pe.edu.upc.entities;
// Generated 01-jul-2017 17:48:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distritos generated by hbm2java
 */
public class Distritos  implements java.io.Serializable {


     private Integer id;
     private Provincias provincias;
     private String nombre;
     private Set servicioses = new HashSet(0);

    public Distritos() {
    }

	
    public Distritos(Provincias provincias, String nombre) {
        this.provincias = provincias;
        this.nombre = nombre;
    }
    public Distritos(Provincias provincias, String nombre, Set servicioses) {
       this.provincias = provincias;
       this.nombre = nombre;
       this.servicioses = servicioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Provincias getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Provincias provincias) {
        this.provincias = provincias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getServicioses() {
        return this.servicioses;
    }
    
    public void setServicioses(Set servicioses) {
        this.servicioses = servicioses;
    }




}


