package pe.edu.upc.entities;
// Generated 01-jul-2017 17:48:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer id;
     private Servicios servicios;
     private Usuarios usuarios;
     private String fecha;
     private String observaciones;
     
     private Set reclamoses = new HashSet(0);

    public Pedidos() {
    }

	
    public Pedidos(Servicios servicios, Usuarios usuarios, String fecha) {
        this.servicios = servicios;
        this.usuarios = usuarios;
        this.fecha = fecha;
        
    }
    public Pedidos(Servicios servicios, Usuarios usuarios, String fecha, String observaciones, Set reclamoses) {
       this.servicios = servicios;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.observaciones = observaciones;
       this.reclamoses = reclamoses;
       
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set getReclamoses() {
        return this.reclamoses;
    }
    
    public void setReclamoses(Set reclamoses) {
        this.reclamoses = reclamoses;
    }

 



}


