package pe.edu.upc.entities;
// Generated 01-jul-2017 17:48:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias  implements java.io.Serializable {


     private Integer id;
     private Departamentos departamentos;
     private String nombre;
     private Set distritoses = new HashSet(0);
     private Set servicioses = new HashSet(0);

    public Provincias() {
    }

	
    public Provincias(Departamentos departamentos, String nombre) {
        this.departamentos = departamentos;
        this.nombre = nombre;
    }
    public Provincias(Departamentos departamentos, String nombre, Set distritoses, Set servicioses) {
       this.departamentos = departamentos;
       this.nombre = nombre;
       this.distritoses = distritoses;
       this.servicioses = servicioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDistritoses() {
        return this.distritoses;
    }
    
    public void setDistritoses(Set distritoses) {
        this.distritoses = distritoses;
    }
    public Set getServicioses() {
        return this.servicioses;
    }
    
    public void setServicioses(Set servicioses) {
        this.servicioses = servicioses;
    }




}


